fix deploy file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -84,16 +84,18 @@ jobs:
                   script: |
                       cd /home/${{ env.PROJECT_NAME }}
                       if [ ! -f ${{ env.PROJECT_NAME }}.tar ]; then
-                        echo "Docker image file not found!"
-                        exit 1
+                      echo "Docker image file not found!"
+                      exit 1
                       fi
                       old_image=$(docker images -q ${{ env.PROJECT_NAME }}:latest)
                       if [ -n "$old_image" ]; then
-                        docker rmi -f $old_image
+                      docker rmi -f $old_image
                       fi
                       docker load -i ${{ env.PROJECT_NAME }}.tar
-                      docker compose down
-                      docker compose up -d
-
+                      
+                      # Pass environment variables directly into docker-compose command
+                      PROJECT_NAME=${{ env.PROJECT_NAME }} PROJECT_PORT=${{ env.PROJECT_PORT }} docker compose down
+                      PROJECT_NAME=${{ env.PROJECT_NAME }} PROJECT_PORT=${{ env.PROJECT_PORT }} docker compose up -d
+                      
             - name: Cleanup local Docker image tar
               run: rm ${{ env.PROJECT_NAME }}.tar
